# docker-compose file for automating the deployment
# of a basic test bootstrap node.

version: '2'
services:
  proxy:
    build: nginx-proxy/
    ports:
      - "443:443"
    depends_on:
      - etcd
  etcd:
    image: quay.io/coreos/etcd
    command: >
      --listen-client-urls 'http://etcd:2379'
      --advertise-client-urls 'http://etcd:2379'
